# Generated by Django 5.1.6 on 2026-04-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='chest_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
